# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5460600b7466757a5003f808b26d85f90e1886739cdc9ce834a1e798c6919730e61859123a2c39df6d9b7bbfba3327a593ec80ddfc4e8a7f7cd1a67a4de46de7

test:
  secret_key_base: 443af6f05c8655ad7139cdaafb724584072a9b739ab4b5ce742e1e44993492ff32e57c0f98178030d29443f99977723d8489ec23f3e92fb5cb2ed74de9bb19b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
